export declare class EventService {
    createEvent(organizerId: number, data: any): Promise<{
        createdAt: Date;
        updatedAt: Date;
        id: number;
        title: string;
        description: string;
        location: string;
        category: import("../generated/prisma").$Enums.EventCategory;
        status: import("../generated/prisma").$Enums.EventStatus;
        bannerImage: string | null;
        startAt: Date;
        endAt: Date;
        basePriceIDR: number | null;
        totalSeats: number | null;
        availableSeats: number | null;
        organizerId: number;
    }>;
    updateEvent(eventId: number, organizerId: number, data: any): Promise<{
        createdAt: Date;
        updatedAt: Date;
        id: number;
        title: string;
        description: string;
        location: string;
        category: import("../generated/prisma").$Enums.EventCategory;
        status: import("../generated/prisma").$Enums.EventStatus;
        bannerImage: string | null;
        startAt: Date;
        endAt: Date;
        basePriceIDR: number | null;
        totalSeats: number | null;
        availableSeats: number | null;
        organizerId: number;
    }>;
    deleteEvent(eventId: number, organizerId: number): Promise<{
        createdAt: Date;
        updatedAt: Date;
        id: number;
        title: string;
        description: string;
        location: string;
        category: import("../generated/prisma").$Enums.EventCategory;
        status: import("../generated/prisma").$Enums.EventStatus;
        bannerImage: string | null;
        startAt: Date;
        endAt: Date;
        basePriceIDR: number | null;
        totalSeats: number | null;
        availableSeats: number | null;
        organizerId: number;
    }>;
    listEvents(params: any): Promise<{
        organizer: {
            rating: number;
            reviewCount: number;
            name: string | null;
            profileImg: string | null;
            id: number;
        };
        createdAt: Date;
        updatedAt: Date;
        id: number;
        title: string;
        description: string;
        location: string;
        category: import("../generated/prisma").$Enums.EventCategory;
        status: import("../generated/prisma").$Enums.EventStatus;
        bannerImage: string | null;
        startAt: Date;
        endAt: Date;
        basePriceIDR: number | null;
        totalSeats: number | null;
        availableSeats: number | null;
        organizerId: number;
    }[]>;
    getOrganizerEvents(organizerId: number): Promise<{
        createdAt: Date;
        updatedAt: Date;
        id: number;
        title: string;
        description: string;
        location: string;
        category: import("../generated/prisma").$Enums.EventCategory;
        status: import("../generated/prisma").$Enums.EventStatus;
        bannerImage: string | null;
        startAt: Date;
        endAt: Date;
        basePriceIDR: number | null;
        totalSeats: number | null;
        availableSeats: number | null;
        organizerId: number;
    }[]>;
    getEventDetails(eventId: number): Promise<{
        organizer: {
            rating: number;
            reviewCount: number;
            name: string | null;
            profileImg: string | null;
            id: number;
        };
        reviews: {
            createdAt: Date;
            id: number;
            userId: number;
            eventId: number;
            rating: number;
            comment: string | null;
        }[];
        ticketTypes: {
            name: string;
            createdAt: Date;
            updatedAt: Date;
            id: number;
            totalSeats: number;
            availableSeats: number;
            priceIDR: number;
            eventId: number;
        }[];
        vouchers: {
            createdAt: Date;
            id: number;
            organizerId: number;
            eventId: number;
            code: string;
            discountType: import("../generated/prisma").$Enums.DiscountType;
            discountValue: number;
            startsAt: Date;
            endsAt: Date;
            maxUses: number | null;
            usedCount: number;
            isActive: boolean;
        }[];
        createdAt: Date;
        updatedAt: Date;
        id: number;
        title: string;
        description: string;
        location: string;
        category: import("../generated/prisma").$Enums.EventCategory;
        status: import("../generated/prisma").$Enums.EventStatus;
        bannerImage: string | null;
        startAt: Date;
        endAt: Date;
        basePriceIDR: number | null;
        totalSeats: number | null;
        availableSeats: number | null;
        organizerId: number;
    }>;
    createTicketType(eventId: number, data: any): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: number;
        totalSeats: number;
        availableSeats: number;
        priceIDR: number;
        eventId: number;
    }>;
    updateTicketType(ticketTypeId: number, organizerId: number, data: any): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: number;
        totalSeats: number;
        availableSeats: number;
        priceIDR: number;
        eventId: number;
    }>;
    deleteTicketType(ticketTypeId: number, organizerId: number): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: number;
        totalSeats: number;
        availableSeats: number;
        priceIDR: number;
        eventId: number;
    }>;
}
declare const _default: EventService;
export default _default;
//# sourceMappingURL=event.service.d.ts.map